# Generated by Django 3.2.4 on 2024-02-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchased',
            field=models.IntegerField(default=0),
        ),
    ]
