# Generated by Django 3.2.4 on 2024-02-23 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_withdraw_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Withdraw_Request',
        ),
    ]
