# Generated by Django 3.2.4 on 2024-02-23 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_delete_withdraw_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
