# Generated by Django 3.2.4 on 2024-02-29 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.courses'),
        ),
    ]
