# Generated by Django 3.2.4 on 2024-02-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='edition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
