# Generated by Django 3.2.4 on 2024-02-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20240301_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publisher',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
