# Generated by Django 3.2.4 on 2024-03-03 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_buldles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buldles',
            new_name='Bundle',
        ),
    ]
