# Generated by Django 3.2.4 on 2024-03-04 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_rename_buldles_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bundle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product_images/'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bundle',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.product'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='purchased',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bundle',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='course',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.courses'),
        ),
        migrations.AlterField(
            model_name='product',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.institute'),
        ),
    ]
