# Generated by Django 3.2.4 on 2024-03-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20240305_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='product',
        ),
        migrations.AddField(
            model_name='bundle',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='bundles', to='store.Product'),
        ),
    ]
