# Generated by Django 3.2.4 on 2024-03-05 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20240305_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='image',
        ),
    ]
