# Generated by Django 3.2.4 on 2024-04-25 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20240405_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bundle',
            options={'verbose_name_plural': 'All Bundle'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Doc Categories'},
        ),
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name_plural': 'Doc Course'},
        ),
        migrations.AlterModelOptions(
            name='institute',
            options={'verbose_name_plural': 'Doc Institutes'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Add Books detail'},
        ),
    ]
