# Generated by Django 3.2.4 on 2024-05-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20240425_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='uploads/product_files/'),
        ),
    ]
