# Generated by Django 3.2.4 on 2024-02-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_percentage', models.FloatField(null=True)),
            ],
            options={
                'verbose_name_plural': 'ChargePrice',
            },
        ),
    ]
