# Generated by Django 3.2.4 on 2024-02-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_costs', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name_plural': 'ServiceCosts',
            },
        ),
    ]
