# Generated by Django 3.2.4 on 2024-02-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_servicecosts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdraw_type', models.FloatField(null=True)),
            ],
            options={
                'verbose_name_plural': 'withdraw_type',
            },
        ),
    ]
