# Generated by Django 3.2.4 on 2024-02-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_withdraw_type_withdraw_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw_request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Waiting', 'Waiting'), ('Approved', 'Approved'), ('Failed', 'Failed')], default='Pending', max_length=50),
        ),
    ]
