# Generated by Django 3.2.4 on 2024-02-26 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20240226_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copyright_request',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Q_n_A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active')], default='Active', max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Q_n_A', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
