# Generated by Django 3.2.4 on 2024-02-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20240227_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='q_n_a',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='q_n_a',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
