# Generated by Django 3.2.4 on 2024-02-26 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20240227_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='q_n_a',
            name='user',
        ),
    ]
