# Generated by Django 3.2.4 on 2024-02-26 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_average_rating'),
        ('core', '0011_remove_q_n_a_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='q_n_a',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='store.category'),
        ),
    ]
