# Generated by Django 3.2.4 on 2024-02-27 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_q_n_a_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='q_n_a',
            old_name='user',
            new_name='category',
        ),
    ]
