# Generated by Django 3.2.4 on 2024-02-27 00:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_user_q_n_a_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='q_n_a',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
