# Generated by Django 3.2.4 on 2024-03-01 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0014_product_publisher'),
        ('core', '0015_rename_q_n_a_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_answer',
            name='category',
        ),
        migrations.AddField(
            model_name='question_answer',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='store.product'),
        ),
        migrations.AddField(
            model_name='question_answer',
            name='question_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question_answer',
            name='question_type',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='question_answer',
            name='short_answer',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='question_answer',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question_answer',
            name='answer',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='question_answer',
            name='question',
            field=models.TextField(default=None),
        ),
    ]
