# Generated by Django 3.2.4 on 2024-03-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_question_answer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_answer',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
