# Generated by Django 3.2.4 on 2024-03-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20240304_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_answer',
            name='chapter_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
