# Generated by Django 3.2.4 on 2024-04-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_question_answer_chapter_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qna_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
    ]
