# Generated by Django 3.2.4 on 2024-04-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_qna_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header_Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('tag', models.TextField(null=True)),
            ],
        ),
    ]
