# Generated by Django 3.2.4 on 2024-04-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_header_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='QA_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'QA_Types',
            },
        ),
    ]
