# Generated by Django 3.2.4 on 2024-04-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_question_answer_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Latest_Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Latest Articles',
            },
        ),
        migrations.AlterModelOptions(
            name='chargeprice',
            options={'verbose_name_plural': 'Service Charge Percentage'},
        ),
        migrations.AlterModelOptions(
            name='copyright_request',
            options={'verbose_name_plural': 'All Copyright Request'},
        ),
        migrations.AlterModelOptions(
            name='qa_types',
            options={'verbose_name_plural': 'Question Answer Types'},
        ),
        migrations.AlterModelOptions(
            name='qna_price',
            options={'verbose_name_plural': 'Question Anaswer Price'},
        ),
        migrations.AlterModelOptions(
            name='question_answer',
            options={'verbose_name_plural': 'All Question Answer'},
        ),
        migrations.AlterModelOptions(
            name='servicecosts',
            options={'verbose_name_plural': 'Sales Tax'},
        ),
        migrations.AlterModelOptions(
            name='withdraw_request',
            options={'verbose_name_plural': 'All Withdraw Request'},
        ),
        migrations.AlterModelOptions(
            name='withdraw_type',
            options={'verbose_name_plural': 'Account Withdraw Types'},
        ),
    ]
