# Generated by Django 3.2.4 on 2024-04-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20240425_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latest_articles',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
